#!/bin/sh

# Ape version should only be defined in edit.h
version=`./version.sh | cut -d . -f 1-3`
printf "Version = ${version}\n"

printf "This will sync everything in your ~/.apeXX to the default distribution.\n"
printf "Are you sure you want to do this? (yes/no) "

read resp
if [ 0"$resp" = 0'yes' ]; then
    rsync -av --delete --exclude '.svn' ~/.ape-${version}/Languages/ Aperc/Languages
    rsync -v ~/.ape-${version}/options.rc Aperc
    rsync -v ~/.ape-${version}/custom_menu Aperc
else
    printf "Cancelled.\n"
fi
git diff
