#!/bin/sh

# Ape version should only be defined in edit.h
version=`./version.sh | cut -d . -f 1-3`
printf "Version = ${version}\n"

printf "This will sync everything in your ~/.apeXX to the default distribution.\n"
printf "Are you sure you want to do this? y/[n] "

read resp
if [ 0"$resp" = 0y ]; then
    rsync -av --delete --exclude '.svn' ~/.ape-${version}/Languages/ Aperc/Languages
    rsync -v ~/.ape-${version}/options.rc Aperc
    rsync -v ~/.ape-${version}/custom_menu Aperc
    git diff
else
    printf "Canceled.\n"
fi

