#!/bin/sh

if [ $# != 1 ]; then
    printf "Usage: $0 filename\n"
    exit 1
fi

filename=$1

if [ -L $filename ]; then
    printf "$0: Error: $filename is a link, and aspell breaks links.\n"
    exit 1
fi

case ${filename#*.} in
    dbk|xdbk|html|xml|sgml)
	aspell -H check $filename
	;;
    tex)
	aspell -t check $filename
	;;
    1|2|3|4|5|6|7|8|9|man)
	aspell -n check $filename
	;;
    *)
	aspell check $filename
	;;
esac

